### ISSUE TITLE
File upload strategy

### ISSUE THREAD

**Issue by NickPapacostas** [SocialHackersClass10/ChalleduApp#14]
Decide on the best solution for allowing file uploads on the backend.

Research alternative solutions:
- watch videos
- google "file uploading in node and mongo 2020" 

etc

**Comment by student0b4dc0d3** [comment]
Good morning team.

I have a few questions for tonight's meeting session:
- What are the documents we expect the users to upload about
- How large are we expecting a single document to be?

I am asking because mongoDB seems to have a "document" size limit of 16 MB.

If any one atomic file upload is never expected to reach that limit, we could encode and store each as a unique document, possibly without any further required chunking tech.

T.y. and have an awesome productive day

**Comment by zannis** [comment]
> * What are the documents we expect the users to upload about

We expect these to be pdf documents or images.

> * How large are we expecting a single such document to be?

There is no clear requirement, but given the 16MB limitation from mongodb, we will accept it as the maximum size for a document upload. We need to have a self-contained datastore so that we can accommodate the requirement that the app can run on the customer's premises without the need for external storage providers.

**Comment by student0b4dc0d3** [comment]
It seems that the data store can be self-contained on the customer's servers regardless of hosted / stored resource upload size.

The tech suggests that atomic resources larger than 16 MB, will be segmented in chunks of manageable (and definable) size, so as to honour the mongo doc limitations ( hence my reference to "chunking tech" ).

The difference seems to be in the access and retrieval of said resources, since, in case of large sizes, it seems to need X+1 AJAX requests to retrieve the complete resource ( where X is the number of stored chunks )

At least that is the gist of what I have collected so far.

If anyone has an idea or would like to point out a specific direction, I am more than happy to look into it
Thank you

**Comment by ligopsychakis-michalis** [comment]
Hello team.. Zannis suggested for the upload of files to use 'Gridfs' and 'formidable'.. I want to ask why we need the 'formidable' package... Cause if I understood corectly we can store the files to mongodb just with 'G0ridfs'...

**Comment by student0b4dc0d3** [comment]
I seem to have overlooked the "formidable" reference completely.

Imo, Zannis was suggesting possible techs / methodologies, not necessarily trying to force a specific method over another.

I assume formidable was mentioned to point to an alternative, for a case where we couldn't ( or didn't want to ) include upload resource storage into mongodb

**Comment by student0b4dc0d3** [comment]
Another question for tonight's team meeting session:
What is the App going to do with said uploaded resources?
Are we supposed to offer access to the userbase? render for read? print? offer a download?

**Comment by zannis** [comment]
@student0b4dc0d3  Interesting analysis. Looks like mongo support for large binary objects is pretty mature and can handle many usecases which gives us security and future-proofing for this decision.

For the time being let's not worry further about splitting binary files into chunks as we are **not** going to support this as part of this project. 

@ligopsychakis-michalis  I mentioned the formidable package because when saving files, we are going to need an endpoint for the file upload. When POSTing a binary file, its contents are binary data that are usually split into multiple requests and use the header 'Content-Type' : 'multipart/form-data'. Express **can't** handle file upload from such requests on its own so it will need a library to do that. There _are_ alternative options here and as @student0b4dc0d3 mentions, 'formidable' was just a suggestion that I am familiar with. But we definitely need to consider the complete data-flow: how the data will be received from the HTTP requests as chunks (or multipart form data), then how they will be merged to a single binary file (formidable helps with that) which then mongodb (and gridfs) will be able to handle, validate and save. I am always open for further discussion and alternatives on the topic.

> What is the App going to do with said uploaded resources?
Essentially we need CRUD endpoints for these resources, 1 to POST them, another one to GET them (with the proper content-type, so that the frontend can render them appropriately), and a third one to DELETE them.

> Are we supposed to offer access to the userbase? render for read? print? offer a download?
All options are still open, and as the backend team we don't really have to care about how the frontend will display them. We just need to make sure we serve the requested contents with the proper Content-Type header.

Let me know if that makes sense and lets try to finalize this by the end of our call tonight. Cheers!

**Comment by zannis** [comment]
@zannis Pending further info on how to return objects from GridFS back to the client.

**Comment by ligopsychakis-michalis** [comment]
Hello team!! I saw an alternative to formidable library, the express-formidable and it seems to me easy enough to use.. here is the link https://www.npmjs.com/package/express-formidable ,
it's just a middleware and returns the file with it's characteristics... so what do you think??

**Comment by zannis** [comment]
@ligopsychakis-michalis  good find, but looks kind of outdated. Lets stick to the original lib and we'll figure out any difficulties that may arise. We might end up creating such a lib on our own ;) 
I approved the PR with the 2 dependencies btw, so I'm closing this.
:beer:
