### ISSUE TITLE
Endpoint for creating an NGO in mongoDB

### ISSUE THREAD

**Issue by NickPapacostas** [SocialHackersClass10/ChalleduApp#30]
This should be a POST request under /ngos

Required fields for NGOs are:
    name
    webpage
    description
    main_representative <- contains the user id
    affinities
    contact: {
        address: [{type:String, trim: true}],
        phone: [{type:String, trim: true}],
    }

Acceptance criteria:
1. create the new route
2. update ngo schema to set required fields
3. validate input using middleware and the ngo schema
4. save the input in mongodb
5. in case of success return 201 and a response body like so: 
```
{
    _id: <newly created id>
}
```
if validation fails return 400 with 
```
{
    error: <error message>
}
```
for any other failure return 500 with 
```
{
    error: <error message>
}
```

**Comment by ligopsychakis-michalis** [comment]
Hello team.. I have a question about this ticket..
The User schema has a field for the ngo _id that the user is relative to..
So when we'll create the post route for the ngo we want to know the _id of the user that creates the ngo profile, in order to add to the user's profile the _id of this ngo, right??

**Comment by student0b4dc0d3** [comment]
I am not certain I have completely understood your question, Mike

Yes, some users will be "affiliated" with an NGO, those users' affiliated object fields will have the respective NGO's _id and name fields with the NGO data

On the flip-side, each NGO has a main_representative field, that will be used to point to the "user" _id.
At least, as far as I can remember, that is what we decided in the schema definition phase.
The value for this field should, under normal circumstance, be provided to you together with the rest of the field values, since it is part of the NGO schema.

I hope this helps to clear any confusion.
If I am off-topic then I must have misunderstood your question completely, in which case please ignore this comment.
TY and have a great day Team

**Comment by zannis** [comment]
> So when we'll create the post route for the ngo we want to know the _id of the user that creates the ngo profile, in order to add to the user's profile the _id of this ngo, right??

You are correct @ligopsychakis-michalis , however, since only logged in users will be able to create NGOs, we can assume that whoever is using this endpoint already has access to the user id and will provide it as part of the request body.
Let me know if that is clear or I should provide further info. (This will make more sense after we implement authentication as well.)

**Comment by zannis** [comment]
I also updated the ticket body with details for this ticket ;)

**Comment by ligopsychakis-michalis** [comment]
ok i see.. thanks @zannis && @student0b4dc0d3...

**Comment by ligopsychakis-michalis** [comment]
Iam not sure that I understand the field  "main_representative"... It's gonna be the user that creates the  
NGO's profile??? Because many users can declare that be a member of the same NGO...

**Comment by student0b4dc0d3** [comment]
I think this will contain the "main speaks-person", maybe the person in charge for PR, most probably the person who created this NGO document. 
I also assume you are correct about the relation of users to MGO, it can by design support many to one, which may or may not be the case, but our structure supports it anyway.
The flip-side are users, they may or may not be affiliated with an NGO, also by design and per specifications

**Comment by ligopsychakis-michalis** [comment]
@zannis we made the ticket but we want to ask about the documents.... Is that something that we have to handle on this ticket??? If yes can we talk about it??

**Comment by zannis** [comment]
I actually made a mess while merging, figured it out and pushed the correct changes to master.
