### ISSUE TITLE
Endpoint to get a single NGO

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#44]
Acceptance criteria

Implement GET endpoint under /ngos/:id
This endpoint should return all fields from an NGO
success : 200
```
{
   ngo : {ngo object}
}
```
not found : 404
```
{
   error: 'resource not found'
}
```
other error: 500
```
{
    error: <error message>
}
```

**Comment by bbouba** [comment]
And the case if document_stat is not 'Approved' what kind error must be return?(number and message)

**Comment by student0b4dc0d3** [comment]
Good morning @bbouba 

I would suggest to disregard the document_state value, until we implement a better methodology for how to handle documents with state different than "Approved".

Because, normally we would need to supply a method to request User(s) with an specific value of that field.
It may be a new set of endpoints, like :
* /users/Approved/:id , which would be the normal case request
* /users/Pending/:id* , which would be an admin request to review and decide registrations
* /users/Rejected/:id , which would be an admin request to re-review and possibly edit ( ? offending ? ) document values, after contact with NGO representative.

Under normal, real-life circumstances, the list of all possible methodology would be extensive, I do not think we are prepared to handle such detail, hence my suggestion.
And, it is moderately easy to jump in and rectify this later on, when we have decided on a more detailed methodology.

I hope this helps a little and have a great day

**Comment by bbouba** [comment]
That means, i must do 3 POST endpoint with 3 differents routes?

**Comment by zannis** [comment]
Guys, no reason to overcomplicate things. We are going to use our authentication middleware to handle admin vs regular user and query parameters to get users based on some property. For now lets stick to the acceptance criteria and we will update this endpoint as soon as we have the rest of the required mechanisms in place.
This iteration of this endpoint will return **all** NGOs. Next iteration, will filter for approved / pending / rejected based on the role of the user. Thanks!
